import * as THREE from 'three';

/**
 * Torus - Surface of revolution generated by rotating a circle
 * Topology: Genus-1 surface (single hole)
 * Parameterizable: major radius, minor radius (tube), segments
 */
export function createTorus(
    radius = 1,
    tube = 0.4,
    radialSegments = 8,
    tubularSegments = 12,
    position = { x: 0, y: 0, z: 0 }
) {
    const geometry = new THREE.TorusGeometry(
        radius,
        tube,
        radialSegments,
        tubularSegments
    );
    const material = new THREE.MeshLambertMaterial({
        color: 0x00ff00,
        wireframe: true,
        transparent: true,
        opacity: 0.6,
        emissive: 0x003300,
        emissiveIntensity: 0.2
    });

    const mesh = new THREE.Mesh(geometry, material);
    mesh.position.set(position.x, position.y, position.z);

    return mesh;
}

export const torusInfo = {
    name: 'Torus',
    category: 'Surface of Revolution',
    topology: 'Genus-1 (Euler characteristic χ = 0)',
    parameters: ['radius', 'tube', 'radialSegments', 'tubularSegments']
};
